name: zingmp5
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  carousel_slider: ^5.0.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  just_audio: ^0.9.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  cloud_firestore: ^5.6.7
  firebase_messaging: ^15.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1


flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/banner/
     - assets/slider_image/
     - assets/recommen/
     - assets/lg.jpeg
     - assets/songs.json
     - assets/utm.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/utm.png"  # Đường dẫn đến file icon
  adaptive_icon_background: "#FFFFFF"  # Màu nền cho icon trên Android (Adaptive Icon)
  adaptive_icon_foreground: "assets/utm.png"

